### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by dbhurley** [inevitable-changes/bento#255]
ERC-20 assets failing to propagate. Only NFT's showing in the interface, no console errors.

**Comment by junhoyeo** [comment]
will fix asap with my greatest priotiry

**Comment by dbhurley** [comment]
This update adds a **Crypto/NFT/Badges toolbar** but does not address the underlying "fetch" failure for token assets. 
_(NFT assets look great, btw)_

**Comment by junhoyeo** [comment]
> This update adds a Crypto/NFT/Badges toolbar but does not address the underlying "fetch" failure for token assets.

Hey, thanks for noticing! I also deployed bug fixes where the client can likely fail requests. Can you check again after refreshing the interface?

Just in case, can you confirm you're using the app under `bento.finance` and not other deployments/local?

> NFT assets look great, btw

Gee thanks 🙏
