### ISSUE TITLE
Secret value is hardcoded in card image renderer (used for encrypting parameters, zero severity)

### ISSUE THREAD

**Issue by alllz** [inevitable-changes/bento#386]
> Hardcoded value is used as a cipher key (in crypto.createHmac). Generate the value with a cryptographically strong random number generator and do not hardcode it in source code.
> [packages/bento-api/pages/api/images/card.tsx](https://github.com/inevitable-changes/bento/tree/e8b33c1551a113dbe9eb179ed80837d42f2a3e72/packages/bento-api/pages/api/images/card.tsx#L55)

Let's move this to environment variables someday

**Comment by junhoyeo** [comment]
Removed card sharing feature
